### ISSUE TITLE
Colour not showing orange for preview 

### ISSUE THREAD

**Issue by UnrealBloke** [ThomasMout/Arduino-vMix-tally#2]
Hi. 

Thanks for this amazing project, followed the instructions and its working well with vMix! 

One issues is that the preview icon is showing in red instead of orange as per your example. I have purchased the hardware according to your links. 

Do you have any suggestions? 

Thanks.

**Comment by ThomasMout** [comment]
Hi,

Happy to hear that it's working well.

Unfortunately it is correct that the LED lights are showing red. This is because the LED matrix used only has red LED lights. The difference in color in the preview icon is a result of different LED intensity. When L(ive) is on the intensity is on 100% and when P(review) is on the intensity is 28,5%.

I hope this clarifies things for you. 
If there is anything else I can help you with. Please open a new issue.

Greetings,
Thomas
